---
title: "Interactive Website"
output: html_document
date: "2023-12-23"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Interactive Website for My BF

```{r}
library(shiny)
library(shinyjs)

ui <- fluidPage(
  useShinyjs(),  # Initialize shinyjs
  tags$head(
    tags$style(HTML("
      label {
        color: #333 !important;
        font-size: 30px !important;
      }
    "))
  ),
  div(
    id = "container",
    style = "display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh;",
    tags$form(
      id = "questionForm",
      p("Tu m'aimes?", style = "font-family: 'Comic Sans MS', cursive; font-size: 100px; text-align: center; color: #333;"),
      radioButtons("answer", 
                   h1("Choisis une option:"),  # Use h1 tag to increase the size
                   c("Oui" = "yes",
                     "Non" = "no"), inline = TRUE),
      br(),
      actionButton("submitBtn", "Soumettre", style = "display: block; margin: 20px auto;")
    ),
    br(),
    uiOutput("gifOutput", style = "text-align: center; margin-top: 50px;")
  )
)

server <- function(input, output) {
  observeEvent(input$submitBtn, {
    if (input$answer == "yes") {
      output$gifOutput <- renderUI({
        tags$img(
          src = "https://media4.giphy.com/media/toYIS95xETUPLmU9WP/200w.gif?cid=6c09b952uoagrq3edqz7fn3ytpe3kv2nrnlellcb9s307nx7&ep=v1_gifs_search&rid=200w.gif&ct=g",
          alt = "Yes GIF",
          style = "width: 500px; height: 500px;"
        )
      })
    } else if (input$answer == "no") {
      output$gifOutput <- renderUI({
        tags$img(
          src = "https://media.tenor.com/HFTGp2mOONcAAAAM/cry-crying.gif",
          alt = "No GIF",
          style = "width: 500px; height: 500px;"
        )
      })
    }
  })
  
  # Set background image with size using shinyjs
  shinyjs::runjs('document.body.style.backgroundImage = "url(\'https://i.pinimg.com/564x/70/b7/11/70b71114a4074364a6412d205a551e39.jpg\')";
                  document.body.style.width = "100%";
                  document.body.style.height = "100%";
                  document.body.style.backgroundSize = "cover";
                  document.body.style.backgroundRepeat = "no-repeat";')
}

shinyApp(ui = ui, server = server)


``` 

```{r}
getwd()
setwd("/Users/rossetantonin/Desktop/website/webidoga")
```


```{r}
#install.packages('rsconnect')
library(rsconnect)
rsconnect::accounts()
rsconnect::setAccountInfo(name='dogacannnnn', token='AC2CE2A8280FDA826BBD3C491B7BA4A8', secret='Nl7ddqUch1tfnBTAKUeVzyjpk661sCpo/Vm0K03p')
#rsconnect::deployApp() 
#abonnement shinyapps.io obligatoire
```


